import { Router } from 'express'
import { createHash } from 'node:crypto'
import jwt from 'jsonwebtoken'
import multer from 'multer'
import { z } from 'zod'
import { env } from '../config/env.js'
import { Attendance } from '../models/Attendance.js'
import { Employee } from '../models/Employee.js'
import { FaceAttendanceRequest } from '../models/FaceAttendanceRequest.js'
import { asyncHandler } from '../utils/asyncHandler.js'
import { HttpError } from '../utils/httpError.js'
import { createManualAttendanceRequest, normalizeDeviceDetails, reviewManualAttendanceRequest } from '../services/manualAttendanceService.js'
import { fetchAttendanceProof } from '../services/privateStorageService.js'

const router=Router()
const livePhotoUpload=multer({storage:multer.memoryStorage(),limits:{fileSize:4_500_000},fileFilter:(_req,file,done)=>done(null,['image/jpeg','image/png','image/webp'].includes(file.mimetype))})
const location=z.object({latitude:z.number().min(-90).max(90),longitude:z.number().min(-180).max(180),accuracyMeters:z.number().positive().max(10000),address:z.string().max(300).optional()}).optional()
const schema=z.object({action:z.enum(['check_in','check_out']),attendanceMode:z.enum(['office','wfh','client_location','field_visit']).default('office'),reasonCode:z.enum(['LIVE_CAMERA_VERIFICATION','CAMERA_PERMISSION_DENIED','CAMERA_NOT_AVAILABLE','CAMERA_INITIALIZATION_FAILED','CAMERA_CAPTURE_FAILED','NO_FACE_DETECTED','FACE_NOT_DETECTED','MULTIPLE_FACES','POOR_IMAGE_QUALITY','LIVENESS_FAILED','FACE_MATCH_FAILED','FACE_MISMATCH','LOCATION_PERMISSION_DENIED','LOCATION_FAILED','NETWORK_FAILED','NETWORK_OR_DEVICE_ERROR','BIOMETRIC_SERVICE_UNAVAILABLE','BROWSER_NOT_SUPPORTED','UNKNOWN_ERROR','OTHER']),remarks:z.string().trim().max(1000).default(''),location,proofPhoto:z.string().startsWith('data:image/').max(4_500_000).optional(),mismatchToken:z.string().min(20).optional(),clientRequestId:z.string().uuid().optional(),deviceDetails:z.object({browser:z.string().max(1000).optional(),os:z.string().max(1000).optional(),deviceType:z.string().max(1000).optional()}).transform(normalizeDeviceDetails).optional(),biometricAttempt:z.object({attempts:z.number().int().min(0).max(20).default(0),technicalErrorCode:z.string().max(80).optional(),cameraStatus:z.enum(['not_attempted','working','failed']).default('not_attempted'),livenessStatus:z.enum(['not_attempted','passed','failed','unknown']).default('not_attempted'),faceMatchStatus:z.enum(['not_attempted','passed','failed','unknown']).default('not_attempted'),faceMatchScore:z.number().min(0).max(1).optional()}).default({})})
const populate=query=>query.populate('employee','firstName lastName employeeCode department designation manager').populate('reviewedBy','firstName lastName role').populate('attendance','date checkIn checkOut status attendanceMode')
router.post('/',livePhotoUpload.single('photo'),asyncHandler(async(req,res)=>{const body=req.file?{...req.body,location:req.body.location?JSON.parse(req.body.location):undefined,deviceDetails:req.body.deviceDetails?JSON.parse(req.body.deviceDetails):undefined,biometricAttempt:req.body.biometricAttempt?JSON.parse(req.body.biometricAttempt):undefined}:req.body;const input=schema.parse(body);let proof=null;if(input.mismatchToken){try{proof=jwt.verify(input.mismatchToken,env.jwtSecret)}catch{throw new HttpError(401,'Face mismatch proof expired. Repeat verification')}const proofHash=input.proofPhoto?createHash('sha256').update(input.proofPhoto).digest('hex'):null;if(proof.purpose!=='biometric_mismatch'||proof.sub!==req.user.id||(proof.employeeId&&proof.employeeId!==String(req.user.employee?._id))||proof.mode.replace('-','_')!==input.action||(proof.attendanceMode&&proof.attendanceMode!==input.attendanceMode)||!proofHash||proof.photoHash!==proofHash)throw new HttpError(401,'Invalid face mismatch proof')}const result=await createManualAttendanceRequest({req,input,mismatchProof:proof,proofPhotoSource:req.file?.buffer});res.status(201).json({success:true,data:result})}))
router.get('/',asyncHandler(async(req,res)=>{const elevated=['super_admin','admin','hr_admin'].includes(req.user.role);let filter={employee:req.user.employee?._id};if(req.query.scope==='all'&&elevated)filter={};else if(req.query.scope==='all'&&req.user.role==='manager'){const directReports=await Employee.find({manager:req.user.employee?._id}).distinct('_id');filter={employee:{$in:directReports}}}const rows=await populate(FaceAttendanceRequest.find(filter)).sort({requestedAt:-1}).limit(200);res.json({success:true,data:rows});}))
router.get('/metrics',asyncHandler(async(req,res)=>{if(!['super_admin','admin','hr_admin','it_admin'].includes(req.user.role))throw new HttpError(403,'Insufficient permissions');const since=req.query.from?new Date(req.query.from):new Date(new Date().getFullYear(),new Date().getMonth(),1),match={requestedAt:{$gte:since}};const [total,pending,approved,rejected,highRisk,biometricSuccess]=await Promise.all([FaceAttendanceRequest.countDocuments(match),FaceAttendanceRequest.countDocuments({...match,status:'pending'}),FaceAttendanceRequest.countDocuments({...match,status:'approved'}),FaceAttendanceRequest.countDocuments({...match,status:'rejected'}),FaceAttendanceRequest.countDocuments({...match,riskLevel:'high'}),Attendance.countDocuments({date:{$gte:since},'checkIn.source':'biometric'})]);res.json({success:true,data:{total,pending,approved,rejected,highRisk,biometricSuccess,failureRate:total+biometricSuccess?Number((total/(total+biometricSuccess)*100).toFixed(1)):0}})}))
router.get('/:id/proof',asyncHandler(async(req,res)=>{const request=await populate(FaceAttendanceRequest.findById(req.params.id));if(!request)throw new HttpError(404,'Request not found');const elevated=['super_admin','admin','hr_admin'].includes(req.user.role),manager=req.user.role==='manager'&&String(request.employee?.manager)===String(req.user.employee?._id);if(!elevated&&!manager&&String(request.requestedBy)!==String(req.user._id))throw new HttpError(403,'You cannot view this proof');const proof=await fetchAttendanceProof(request);res.type(proof.contentType).send(proof.buffer)}))
router.patch('/:id/:decision',asyncHandler(async(req,res)=>{if(!['approve','reject'].includes(req.params.decision))throw new HttpError(400,'Invalid decision');const {reviewNote}=z.object({reviewNote:z.string().trim().max(500).default('')}).parse(req.body);const result=await reviewManualAttendanceRequest({req,id:req.params.id,decision:req.params.decision,reviewNote});res.json({success:true,data:await populate(FaceAttendanceRequest.findById(result._id))})}))
export default router
