import { Router } from 'express'
import multer from 'multer'
import { z } from 'zod'
import { authenticate, authorize } from '../middleware/auth.js'
import { asyncHandler } from '../utils/asyncHandler.js'
import { HttpError } from '../utils/httpError.js'
import { User } from '../models/User.js'
import { Employee } from '../models/Employee.js'
import { OrganizationProfile } from '../models/Organization.js'
import { Candidate, CandidateActivity, CandidateCommunication, CandidateDocument, Interview, InterviewFeedback, JobOpening, Notification, OfferApproval, OfferLetter, OfferTemplate, RecruitmentSetting } from '../models/Recruitment.js'
import { candidateStages, createPublicOfferToken, generateOfferPdf, notifyRoles, recordActivity, validateCandidateTransition } from '../services/recruitmentService.js'
import { sendGraphEmail } from '../services/mailService.js'
import { env } from '../config/env.js'

const router = Router()
const hrRoles = ['super_admin','hr_admin']
const upload = multer({ storage:multer.memoryStorage(), limits:{fileSize:5*1024*1024}, fileFilter:(_req,file,cb) => cb(null,['application/pdf','image/jpeg','image/png','image/webp'].includes(file.mimetype)) })
const optionalString = z.string().optional().or(z.literal(''))
const optionalNumber = z.coerce.number().nonnegative().optional()
const candidateInput = z.object({
  firstName:z.string().min(1), middleName:optionalString, lastName:z.string().min(1), photo:optionalString, email:z.email(), mobile:z.string().min(7), alternateMobile:optionalString,
  dateOfBirth:z.coerce.date().optional(), gender:optionalString, currentCity:optionalString, address:optionalString, preferredLocation:optionalString, pan:optionalString,
  position:z.string().min(1), department:z.string().min(1), designation:optionalString, employmentType:z.enum(['Permanent','Probation','Contract','Internship','Consultant']).optional(), workLocation:optionalString,
  hiringManager:z.string().optional(), recruiter:z.string().optional(), source:optionalString, expectedJoiningDate:z.coerce.date().optional(), totalExperience:optionalNumber, relevantExperience:optionalNumber,
  currentCompany:optionalString, currentDesignation:optionalString, currentCTC:optionalNumber, expectedCTC:optionalNumber, noticePeriod:optionalString, lastWorkingDate:z.coerce.date().optional(), negotiableNoticePeriod:z.boolean().optional(),
  skills:z.array(z.string()).optional(), qualification:optionalString, employmentStatus:z.enum(['Employed','Serving Notice Period','Unemployed','Fresher']).optional(), notes:optionalString, duplicateOverride:z.boolean().optional(),
})

router.use(authenticate)

router.get('/dashboard', authorize(...hrRoles), asyncHandler(async (_req,res) => {
  const [stageCounts, interviewCounts, offerCounts, recentCandidates, interviews] = await Promise.all([
    Candidate.aggregate([{ $group:{ _id:'$currentStage', count:{ $sum:1 } } }]), Interview.aggregate([{ $group:{ _id:'$status', count:{ $sum:1 } } }]),
    OfferLetter.aggregate([{ $group:{ _id:'$status', count:{ $sum:1 } } }]), Candidate.find().sort({updatedAt:-1}).limit(8),
    Interview.find({ date:{ $gte:new Date(new Date().setHours(0,0,0,0)) } }).populate('candidate','firstName lastName position').populate('interviewers','firstName lastName').sort({date:1}).limit(8),
  ])
  res.json({success:true,data:{stageCounts:Object.fromEntries(stageCounts.map(x=>[x._id,x.count])),interviewCounts:Object.fromEntries(interviewCounts.map(x=>[x._id,x.count])),offerCounts:Object.fromEntries(offerCounts.map(x=>[x._id,x.count])),recentCandidates,interviews,stages:candidateStages}})
}))

router.get('/candidates', authorize(...hrRoles), asyncHandler(async (req,res) => {
  const filter={}
  if(req.query.search) filter.$text={$search:req.query.search}
  for(const field of ['department','source','currentStage','status','position']) if(req.query[field]) filter[field]=req.query[field]
  const items=await Candidate.find(filter).populate('recruiter hiringManager','firstName lastName').sort({updatedAt:-1}).limit(200)
  res.json({success:true,data:items})
}))
router.post('/candidates', authorize(...hrRoles), asyncHandler(async (req,res) => {
  const input=candidateInput.parse(req.body)
  const duplicate=await Candidate.findOne({$or:[{email:input.email.toLowerCase()},{mobile:input.mobile},...(input.pan?[{pan:input.pan.toUpperCase()}]:[])]})
  if(duplicate&&!input.duplicateOverride) throw new HttpError(409,'A candidate with the same email, mobile number or PAN already exists.',{existingCandidateId:duplicate.id})
  if(duplicate&&req.user.role!=='super_admin') throw new HttpError(403,'Only Super Admin can continue with a possible duplicate candidate')
  const candidate=await Candidate.create({...input,candidateCode:`CAND-${Date.now().toString().slice(-6)}`,createdBy:req.user._id,updatedBy:req.user._id})
  await recordActivity(req,{action:'Candidate Created',candidate:candidate._id,message:`Candidate created by ${req.user.firstName} ${req.user.lastName}`})
  res.status(201).json({success:true,data:candidate})
}))
router.get('/candidates/:id', authorize(...hrRoles), asyncHandler(async (req,res) => {
  const candidate=await Candidate.findById(req.params.id).populate('recruiter hiringManager','firstName lastName email')
  if(!candidate) throw new HttpError(404,'Candidate not found')
  const [interviews,feedback,documents,offers,activity]=await Promise.all([Interview.find({candidate:candidate._id}).populate('interviewers','firstName lastName email').sort({date:-1}),InterviewFeedback.find({candidate:candidate._id}).populate('interviewer','firstName lastName'),CandidateDocument.find({candidate:candidate._id}),OfferLetter.find({candidate:candidate._id}).select('-compensation').sort({version:-1}),CandidateActivity.find({candidate:candidate._id}).populate('performedBy','firstName lastName').sort({createdAt:-1})])
  res.json({success:true,data:{candidate,interviews,feedback,documents,offers,activity}})
}))
router.put('/candidates/:id', authorize(...hrRoles), asyncHandler(async (req,res) => {
  const input=candidateInput.partial().parse(req.body), candidate=await Candidate.findById(req.params.id)
  if(!candidate) throw new HttpError(404,'Candidate not found')
  const oldValues=candidate.toObject(); Object.assign(candidate,input,{updatedBy:req.user._id}); await candidate.save()
  await recordActivity(req,{action:'Candidate Updated',candidate:candidate._id,oldValues,newValues:candidate.toObject(),message:'Candidate details updated'})
  res.json({success:true,data:candidate})
}))
router.patch('/candidates/:id/status', authorize(...hrRoles), asyncHandler(async (req,res) => {
  const {stage}=z.object({stage:z.string()}).parse(req.body), candidate=await Candidate.findById(req.params.id)
  if(!candidate) throw new HttpError(404,'Candidate not found')
  if(['Selected','Offer Draft','Pending Super Admin Approval','Approved','Offer Sent','Offer Viewed','Offer Accepted','Onboarding Pending','Joined'].includes(stage)) throw new HttpError(403,'Use the secured workflow action for this stage')
  validateCandidateTransition(candidate.currentStage,stage,req.user.role); const old=candidate.currentStage; candidate.currentStage=stage; await candidate.save()
  await recordActivity(req,{action:'Candidate Stage Changed',candidate:candidate._id,oldValues:{stage:old},newValues:{stage},message:`Moved from ${old} to ${stage}`})
  res.json({success:true,data:candidate})
}))
router.post('/candidates/:id/documents', authorize(...hrRoles), upload.single('file'), asyncHandler(async (req,res) => {
  if(!req.file) throw new HttpError(422,'A PDF or image document is required')
  const candidate=await Candidate.findById(req.params.id); if(!candidate) throw new HttpError(404,'Candidate not found')
  const document=await CandidateDocument.create({candidate:candidate._id,documentType:req.body.documentType||'Other Supporting Document',fileName:req.file.originalname,mimeType:req.file.mimetype,size:req.file.size,storageKey:`candidate/${candidate.id}/${Date.now()}`,fileData:req.file.buffer,uploadedBy:req.user._id})
  await recordActivity(req,{action:'Candidate Document Uploaded',candidate:candidate._id,message:`${document.documentType} uploaded`}); res.status(201).json({success:true,data:document})
}))
router.get('/documents/:id/download', authorize(...hrRoles), asyncHandler(async (req,res) => { const document=await CandidateDocument.findById(req.params.id).select('+fileData'); if(!document) throw new HttpError(404,'Document not found'); res.set({'Content-Type':document.mimeType,'Content-Disposition':`attachment; filename="${document.fileName.replace(/"/g,'')}"`,'Cache-Control':'private, no-store'}).send(document.fileData) }))

router.get('/interviews', asyncHandler(async (req,res) => {
  const filter={}; if(req.user.role==='manager') filter.interviewers=req.user._id; else if(!hrRoles.includes(req.user.role)) throw new HttpError(403,'You do not have permission for recruitment interviews')
  if(req.query.status) filter.status=req.query.status
  const items=await Interview.find(filter).populate('candidate','candidateCode firstName lastName position department currentStage').populate('interviewers','firstName lastName email').sort({date:1})
  res.json({success:true,data:items})
}))
router.get('/interviews/:id', asyncHandler(async (req,res) => { const interview=await Interview.findById(req.params.id).populate('candidate').populate('interviewers','firstName lastName email'); if(!interview) throw new HttpError(404,'Interview not found'); if(req.user.role==='manager'&&!interview.interviewers.some(x=>x.id===req.user.id)) throw new HttpError(403,'This interview is not assigned to you'); res.json({success:true,data:interview}) }))
router.post('/interviews', authorize(...hrRoles), asyncHandler(async (req,res) => {
  const input=z.object({candidate:z.string(),round:z.string(),interviewType:z.string(),date:z.coerce.date(),startTime:z.string(),endTime:z.string(),interviewers:z.array(z.string()).min(1),meetingMode:z.string(),meetingLink:optionalString,location:optionalString,instructions:optionalString,internalNotes:optionalString}).parse(req.body)
  const candidate=await Candidate.findById(input.candidate); if(!candidate) throw new HttpError(404,'Candidate not found')
  const conflict=await Interview.findOne({interviewers:{$in:input.interviewers},date:input.date,startTime:{$lt:input.endTime},endTime:{$gt:input.startTime},status:{$in:['Scheduled','Rescheduled']}}); if(conflict) throw new HttpError(409,'One or more interviewers are unavailable at this time')
  const interview=await Interview.create({...input,scheduledBy:req.user._id}); if(['New Candidate','Screening','Shortlisted'].includes(candidate.currentStage)) candidate.currentStage='Interview Scheduled'; await candidate.save()
  await recordActivity(req,{action:'Interview Scheduled',candidate:candidate._id,message:`${input.round} scheduled`})
  await Notification.insertMany(input.interviewers.map(recipient=>({recipient,type:'Interview assigned',title:'New interview assigned',message:`${candidate.firstName} ${candidate.lastName} · ${input.round}`,candidate:candidate._id})))
  res.status(201).json({success:true,data:interview})
}))
router.put('/interviews/:id', authorize(...hrRoles), asyncHandler(async (req,res) => { const interview=await Interview.findByIdAndUpdate(req.params.id,req.body,{new:true,runValidators:true}); if(!interview) throw new HttpError(404,'Interview not found'); await recordActivity(req,{action:'Interview Rescheduled',candidate:interview.candidate,message:'Interview details updated'}); res.json({success:true,data:interview}) }))
router.patch('/interviews/:id/status', authorize(...hrRoles), asyncHandler(async (req,res) => { const {status}=z.object({status:z.enum(['Scheduled','Completed','Cancelled','Rescheduled','No Show'])}).parse(req.body), interview=await Interview.findById(req.params.id); if(!interview) throw new HttpError(404,'Interview not found'); interview.status=status; await interview.save(); if(status==='Completed'){const pending=interview.interviewers.map(recipient=>({recipient,type:'Interview feedback pending',title:'Feedback required',message:`Submit feedback for ${interview.round}`,candidate:interview.candidate})); if(pending.length) await Notification.insertMany(pending);const remaining=await Interview.countDocuments({candidate:interview.candidate,status:{$nin:['Completed','Cancelled']}});if(!remaining)await Candidate.findByIdAndUpdate(interview.candidate,{currentStage:'Interview Completed'})} res.json({success:true,data:interview}) }))
router.post('/interviews/:id/feedback', asyncHandler(async (req,res) => {
  const interview=await Interview.findById(req.params.id); if(!interview) throw new HttpError(404,'Interview not found')
  if(!interview.interviewers.some(id=>id.toString()===req.user.id)) throw new HttpError(403,'Only assigned interviewers can submit feedback')
  if(interview.status!=='Completed') throw new HttpError(409,'Feedback can be submitted after interview completion')
  const input=z.object({technicalSkills:z.number().min(1).max(5),communication:z.number().min(1).max(5),problemSolving:z.number().min(1).max(5),roleKnowledge:z.number().min(1).max(5),cultureFit:z.number().min(1).max(5),experienceRelevance:z.number().min(1).max(5),strengths:optionalString,concerns:optionalString,detailedFeedback:z.string().min(3),recommendation:z.enum(['Strong Hire','Hire','Hold','Reject','Strong Reject'])}).parse(req.body)
  const feedback=await InterviewFeedback.create({...input,interview:interview._id,candidate:interview.candidate,interviewer:req.user._id}); interview.feedbackSubmitted=true; await interview.save(); await recordActivity(req,{action:'Feedback Submitted',candidate:interview.candidate,message:`Feedback submitted by ${req.user.firstName} ${req.user.lastName}`}); res.status(201).json({success:true,data:feedback})
}))

router.post('/candidates/:id/select', authorize(...hrRoles), asyncHandler(async (req,res) => { const candidate=await Candidate.findById(req.params.id); if(!candidate) throw new HttpError(404,'Candidate not found'); const interviews=await Interview.find({candidate:candidate._id,status:{$ne:'Cancelled'}}).select('_id status');if(!interviews.length||interviews.some(interview=>interview.status!=='Completed'))throw new HttpError(409,'Complete all required interview rounds before selection');const feedbackInterviewIds=await InterviewFeedback.distinct('interview',{candidate:candidate._id,interview:{$in:interviews.map(interview=>interview._id)}});if(feedbackInterviewIds.length<interviews.length)throw new HttpError(409,'Submit feedback for every completed interview before selecting this candidate'); candidate.selectedDetails=req.body; candidate.currentStage='Selected'; await candidate.save(); await recordActivity(req,{action:'Candidate Selected',candidate:candidate._id,message:`Candidate selected by ${req.user.firstName} ${req.user.lastName}`}); res.json({success:true,data:candidate}) }))
router.post('/candidates/:id/reject', authorize(...hrRoles), asyncHandler(async (req,res) => { const input=z.object({reason:z.string().min(2),remarks:optionalString,sendEmail:z.boolean().optional()}).parse(req.body),candidate=await Candidate.findById(req.params.id); if(!candidate) throw new HttpError(404,'Candidate not found'); candidate.currentStage='Rejected'; candidate.status='Rejected'; candidate.rejection={...input,rejectedBy:req.user._id,rejectedAt:new Date()}; await candidate.save(); await recordActivity(req,{action:'Candidate Rejected',candidate:candidate._id,message:`Candidate rejected: ${input.reason}`}); res.json({success:true,data:candidate}) }))

router.get('/offers', authorize(...hrRoles), asyncHandler(async (_req,res) => { const offers=await OfferLetter.find().populate('candidate','candidateCode firstName lastName email position department').populate('approvedBy submittedBy','firstName lastName').sort({updatedAt:-1}); res.json({success:true,data:offers.filter(offer=>offer.candidate)}) }))
router.get('/offers/:id', authorize(...hrRoles), asyncHandler(async (req,res) => { const offer=await OfferLetter.findById(req.params.id).populate('candidate').populate('approvedBy submittedBy','firstName lastName'); if(!offer) throw new HttpError(404,'Offer not found'); res.json({success:true,data:offer}) }))
router.post('/offers', authorize(...hrRoles), asyncHandler(async (req,res) => { const candidate=await Candidate.findById(req.body.candidate); if(!candidate) throw new HttpError(404,'Candidate not found'); if(!['Selected','Offer Draft'].includes(candidate.currentStage)) throw new HttpError(409,'Candidate must be selected before creating an offer'); const offer=await OfferLetter.create({...req.body,offerCode:`OFF-${Date.now().toString().slice(-7)}`,status:'Draft'}); candidate.currentStage='Offer Draft'; await candidate.save(); await recordActivity(req,{action:'Offer Draft Created',candidate:candidate._id,offer:offer._id,message:'Offer draft created'}); res.status(201).json({success:true,data:offer}) }))
router.put('/offers/:id', authorize(...hrRoles), asyncHandler(async (req,res) => { const offer=await OfferLetter.findById(req.params.id); if(!offer) throw new HttpError(404,'Offer not found'); if(!['Draft','Changes Requested'].includes(offer.status)) throw new HttpError(409,'Only draft or returned offers can be edited'); Object.assign(offer,req.body); if(offer.status==='Changes Requested'){offer.status='Draft';offer.version+=1} await offer.save(); res.json({success:true,data:offer}) }))
router.post('/offers/:id/generate', authorize(...hrRoles), asyncHandler(async (req,res) => { const offer=await OfferLetter.findById(req.params.id).populate('candidate').select('+pdfData'); if(!offer) throw new HttpError(404,'Offer not found'); const organization=await OrganizationProfile.findOne({singletonKey:'organization'}); offer.pdfData=await generateOfferPdf(offer,offer.candidate,organization||{}); offer.pdfFileName=`${offer.candidate.firstName}_${offer.candidate.lastName}_Offer_Letter.pdf`; await offer.save(); await recordActivity(req,{action:'Offer PDF Generated',candidate:offer.candidate._id,offer:offer._id,message:'Offer PDF generated'}); res.json({success:true,data:{id:offer.id,fileName:offer.pdfFileName,status:offer.status}}) }))
router.get('/offers/:id/pdf', authorize(...hrRoles), asyncHandler(async (req,res) => { const offer=await OfferLetter.findById(req.params.id).select('+pdfData'); if(!offer?.pdfData) throw new HttpError(404,'Generate the offer PDF first'); res.set({'Content-Type':'application/pdf','Content-Disposition':`inline; filename="${offer.pdfFileName}"`,'Cache-Control':'private, no-store'}).send(offer.pdfData) }))
router.post('/offers/:id/submit-for-approval', authorize(...hrRoles), asyncHandler(async (req,res) => { const offer=await OfferLetter.findById(req.params.id); if(!offer) throw new HttpError(404,'Offer not found'); if(!['Draft','Changes Requested'].includes(offer.status)) throw new HttpError(409,'This offer cannot be submitted'); offer.status='Pending Super Admin Approval'; offer.submittedBy=req.user._id; offer.submittedAt=new Date(); await offer.save(); await OfferApproval.create({offer:offer._id,candidate:offer.candidate,version:offer.version,submittedBy:req.user._id}); await Candidate.findByIdAndUpdate(offer.candidate,{currentStage:'Pending Super Admin Approval'}); await notifyRoles(User,['super_admin'],{type:'Offer submitted for approval',title:'Offer approval required',message:`${offer.offerCode} requires review`,candidate:offer.candidate,offer:offer._id}); await recordActivity(req,{action:'Offer Submitted for Approval',candidate:offer.candidate,offer:offer._id,message:'Offer sent for Super Admin approval'}); res.json({success:true,data:offer}) }))
router.post('/offers/:id/send', authorize(...hrRoles), asyncHandler(async (req,res) => { const offer=await OfferLetter.findById(req.params.id).populate('candidate').select('+pdfData'); if(!offer) throw new HttpError(404,'Offer not found'); if(offer.status!=='Approved') throw new HttpError(409,'Only an approved offer can be sent'); if(offer.sentAt) throw new HttpError(409,'This offer has already been sent'); if(!offer.pdfData) offer.pdfData=await generateOfferPdf(offer,offer.candidate,await OrganizationProfile.findOne({singletonKey:'organization'})||{}); const {token,hash}=createPublicOfferToken(); const publicUrl=`${env.clientUrl}/public/offers/${token}`; const company=(await OrganizationProfile.findOne({singletonKey:'organization'}))?.companyName||'Our company'; const html=`<div style="font-family:Arial,sans-serif;color:#17213a;line-height:1.7"><h2>Employment Offer – ${offer.designation}</h2><p>Dear ${offer.candidate.firstName},</p><p>We are pleased to offer you the position of <strong>${offer.designation}</strong> with ${company}.</p><p>Please review the approved offer letter attached and <a href="${publicUrl}" style="color:#187b72;font-weight:bold">accept or decline your offer securely</a>.</p><p>Regards,<br>Human Resources<br>${company}</p></div>`; let providerId='development-simulated'; if(!(env.nodeEnv==='development'&&offer.candidate.email.endsWith('.local'))) providerId=await sendGraphEmail({recipient:offer.candidate.email,subject:`Employment Offer – ${offer.designation} at ${company}`,html,attachments:[{name:offer.pdfFileName||'Offer_Letter.pdf',contentType:'application/pdf',content:offer.pdfData}]}); offer.status='Sent'; offer.sentBy=req.user._id; offer.sentAt=new Date(); offer.sentTo=offer.candidate.email; offer.emailProviderMessageId=providerId; offer.secureTokenHash=hash; offer.tokenExpiresAt=new Date(Date.now()+14*24*60*60*1000); await offer.save(); await Candidate.findByIdAndUpdate(offer.candidate._id,{currentStage:'Offer Sent'}); await CandidateCommunication.create({candidate:offer.candidate._id,offer:offer._id,type:'Offer Email',recipient:offer.candidate.email,subject:`Employment Offer – ${offer.designation}`,status:'Sent',providerMessageId:providerId,sentBy:req.user._id}); await recordActivity(req,{action:'Offer Email Sent',candidate:offer.candidate._id,offer:offer._id,message:'Approved offer emailed to candidate'}); const responseOffer=offer.toObject(); delete responseOffer.pdfData; res.json({success:true,data:{offer:responseOffer,developmentAcceptanceUrl:providerId==='development-simulated'?publicUrl:undefined}}) }))

router.get('/offer-approvals', authorize('super_admin'), asyncHandler(async (_req,res) => { const items=await OfferApproval.find().populate({path:'offer',populate:{path:'candidate',select:'candidateCode firstName lastName email position department expectedCTC'}}).populate('submittedBy reviewedBy','firstName lastName').sort({createdAt:-1}); res.json({success:true,data:items.filter(item=>item.offer?.candidate)}) }))
router.get('/offer-approvals/:id', authorize('super_admin'), asyncHandler(async (req,res) => { const approval=await OfferApproval.findById(req.params.id).populate({path:'offer',populate:{path:'candidate'}}).populate('submittedBy reviewedBy','firstName lastName'); if(!approval) throw new HttpError(404,'Approval request not found'); res.json({success:true,data:approval}) }))
for(const action of ['approve','request-changes','reject']) router.post(`/offer-approvals/:id/${action}`,authorize('super_admin'),asyncHandler(async(req,res)=>{const approval=await OfferApproval.findById(req.params.id);if(!approval||approval.status!=='Pending')throw new HttpError(409,'This approval request is no longer pending');const offer=await OfferLetter.findById(approval.offer);if(!offer||offer.status!=='Pending Super Admin Approval')throw new HttpError(409,'Offer is not awaiting approval');const remarks=String(req.body.remarks||'');if(action!=='approve'&&!remarks)throw new HttpError(422,'Remarks are required');approval.reviewedBy=req.user._id;approval.reviewedAt=new Date();approval.remarks=remarks;if(action==='approve'){approval.status='Approved';offer.status='Approved';offer.approvedBy=req.user._id;offer.approvedAt=new Date();offer.approvalRemarks=remarks;offer.immutableSnapshot=offer.toObject();await Candidate.findByIdAndUpdate(offer.candidate,{currentStage:'Approved'})}else if(action==='request-changes'){approval.status='Changes Requested';offer.status='Changes Requested';offer.changesRequestedBy=req.user._id;offer.changesRequestedAt=new Date();offer.changeRemarks=remarks;await Candidate.findByIdAndUpdate(offer.candidate,{currentStage:'Offer Draft'})}else{approval.status='Rejected';offer.status='Rejected';offer.rejectedBy=req.user._id;offer.rejectedAt=new Date();offer.rejectionReason=remarks;await Candidate.findByIdAndUpdate(offer.candidate,{currentStage:'Offer Rejected'})}await Promise.all([approval.save(),offer.save(),Notification.create({recipient:offer.submittedBy,type:`Offer ${approval.status}`,title:`Offer ${approval.status}`,message:remarks||`${offer.offerCode} was approved`,candidate:offer.candidate,offer:offer._id}),recordActivity(req,{action:`Offer ${approval.status}`,candidate:offer.candidate,offer:offer._id,message:remarks||`Offer ${approval.status}`})]);res.json({success:true,data:{approval,offer}})}))

router.get('/offer-templates', authorize(...hrRoles), asyncHandler(async (_req,res)=>res.json({success:true,data:await OfferTemplate.find().sort({createdAt:-1})})))
router.post('/offer-templates', authorize('super_admin'), asyncHandler(async (req,res)=>res.status(201).json({success:true,data:await OfferTemplate.create({...req.body,createdBy:req.user._id})})))
router.get('/job-openings', authorize(...hrRoles), asyncHandler(async (_req,res)=>res.json({success:true,data:await JobOpening.find().sort({createdAt:-1})})))
router.post('/job-openings', authorize(...hrRoles), asyncHandler(async (req,res)=>res.status(201).json({success:true,data:await JobOpening.create(req.body)})))
router.get('/reports/summary', authorize('super_admin'), asyncHandler(async (_req,res)=>{const [sources,departments,stages]=await Promise.all([Candidate.aggregate([{$group:{_id:'$source',count:{$sum:1}}}]),Candidate.aggregate([{$group:{_id:'$department',count:{$sum:1}}}]),Candidate.aggregate([{$group:{_id:'$currentStage',count:{$sum:1}}}])]);res.json({success:true,data:{sources,departments,stages}})}))
router.get('/settings', authorize('super_admin'), asyncHandler(async (_req,res)=>res.json({success:true,data:await RecruitmentSetting.find()})))
router.put('/settings/:key', authorize('super_admin'), asyncHandler(async (req,res)=>res.json({success:true,data:await RecruitmentSetting.findOneAndUpdate({key:req.params.key},{value:req.body.value,updatedBy:req.user._id},{new:true,upsert:true})})))
router.get('/notifications', asyncHandler(async (req,res)=>res.json({success:true,data:await Notification.find({recipient:req.user._id}).sort({createdAt:-1}).limit(50)})))
router.post('/candidates/:id/start-onboarding', authorize(...hrRoles), asyncHandler(async (req,res)=>{const candidate=await Candidate.findById(req.params.id);if(!candidate)throw new HttpError(404,'Candidate not found');if(candidate.currentStage!=='Offer Accepted')throw new HttpError(409,'The candidate must accept the offer first');const offer=await OfferLetter.findOne({candidate:candidate._id,status:'Accepted'}).sort({version:-1});const employee=await Employee.create({employeeCode:`EMP-${Date.now().toString().slice(-6)}`,firstName:candidate.firstName,middleName:candidate.middleName,lastName:candidate.lastName,dateOfBirth:candidate.dateOfBirth,officialEmail:candidate.email,personalEmail:candidate.email,mobile:candidate.mobile,profilePhoto:candidate.photo,department:offer?.department||candidate.department,designation:offer?.designation||candidate.position,workLocation:offer?.workLocation||candidate.workLocation,joiningDate:offer?.joiningDate||candidate.expectedJoiningDate,employmentType:String(offer?.employmentType||candidate.employmentType).toLowerCase().replace('internship','intern'),employeeStatus:'inactive',manager:null,user:null});candidate.currentStage='Onboarding Pending';candidate.onboardingEmployee=employee._id;await candidate.save();await recordActivity(req,{action:'Candidate Converted to Employee',candidate:candidate._id,message:'Employee onboarding draft created'});res.status(201).json({success:true,data:employee})}))

export default router
