import { useEffect, useRef, useState } from 'react'
import { Camera, CheckCircle2, ScanFace, UserRound } from 'lucide-react'
import { createIdentityTemplate, detectFace, loadFaceIdentityModel, loadFaceLandmarker } from './services/biometrics.js'

export default function BiometricEnrollment({ value, onChange }) {
  const videoRef=useRef(null),canvasRef=useRef(null),[stream,setStream]=useState(null),[model,setModel]=useState(null),[identityModel,setIdentityModel]=useState(null),[error,setError]=useState(''),[loading,setLoading]=useState(false)
  useEffect(()=>{if(videoRef.current&&stream){videoRef.current.srcObject=stream;videoRef.current.play().catch(()=>{})}return()=>stream?.getTracks().forEach(track=>track.stop())},[stream])
  async function start(){setLoading(true);setError('');try{const [mediaStream,landmarker,identity]=await Promise.all([navigator.mediaDevices.getUserMedia({video:{facingMode:'user',width:{ideal:640},height:{ideal:480}},audio:false}),loadFaceLandmarker(),loadFaceIdentityModel()]);setModel(landmarker);setIdentityModel(identity);setStream(mediaStream)}catch{setError('Camera or secure face-recognition model is unavailable.')}finally{setLoading(false)}}
  async function capture(){setLoading(true);setError('');try{const result=detectFace(model,videoRef.current);if(!result?.faceLandmarks?.length)throw new Error('No face detected. Center the employee in the frame.');if(result.faceLandmarks.length!==1)throw new Error('Only one employee should be visible.');const canvas=canvasRef.current;canvas.width=640;canvas.height=480;canvas.getContext('2d').drawImage(videoRef.current,0,0,640,480);const profilePhoto=canvas.toDataURL('image/jpeg',.82),biometricTemplate=await createIdentityTemplate(profilePhoto,identityModel);onChange({profilePhoto,biometricTemplate});stream.getTracks().forEach(track=>track.stop());setStream(null)}catch(captureError){setError(captureError.message)}finally{setLoading(false)}}
  if(value?.profilePhoto)return <div className="enrollment-complete"><img src={value.profilePhoto} alt="Employee biometric enrollment"/><div><CheckCircle2 size={17}/><span><strong>Face identity enrolled</strong><small>Recognition embedding captured securely.</small></span></div><button type="button" onClick={()=>{onChange({profilePhoto:'',biometricTemplate:[]});start()}}>Retake</button></div>
  return <div className="biometric-enrollment"><div className="enrollment-copy"><span><ScanFace size={21}/></span><div><h3>Biometric face enrollment *</h3><p>Capture the employee’s live reference photo. This identity embedding is required for attendance face matching.</p></div></div>{stream?<><div className="enrollment-camera"><video ref={videoRef} muted playsInline/><div className="face-guide"/></div><canvas ref={canvasRef} hidden/><button type="button" className="primary-button enrollment-capture" disabled={loading} onClick={capture}><Camera size={16}/>{loading?'Creating secure face identity…':'Capture reference face'}</button></>:<button type="button" className="secondary-button enrollment-start" disabled={loading} onClick={start}><UserRound size={16}/>{loading?'Loading face recognition…':'Open camera for enrollment'}</button>}{error&&<p className="enrollment-error">{error}</p>}</div>
}
