import { useEffect, useMemo, useState } from 'react';
import { AlertTriangle, CheckCircle2, ChevronRight, Clock3, MapPin, ShieldCheck, X } from 'lucide-react';
import { attendanceApi } from './services/api.js';

const reasons=[['CAMERA_NOT_AVAILABLE','Camera not available'],['CAMERA_PERMISSION_DENIED','Camera permission denied'],['FACE_NOT_DETECTED','Face not detected'],['LIVENESS_FAILED','Liveness verification failed'],['FACE_MISMATCH','Face mismatch'],['NETWORK_OR_DEVICE_ERROR','Network or device error'],['BIOMETRIC_SERVICE_UNAVAILABLE','Biometric service unavailable'],['OTHER','Other']];

export default function ManualAttendanceDrawer({action,attendanceMode='office',evidence={},close,submitted}){
  const [reasonCode,setReasonCode]=useState(evidence.reasonCode||'CAMERA_NOT_AVAILABLE'),[remarks,setRemarks]=useState(''),[location,setLocation]=useState(evidence.location||null),[locationWarning,setLocationWarning]=useState(evidence.location?'':navigator.geolocation?'Detecting your current location…':'Location is unavailable. This request will be flagged high-risk.'),[busy,setBusy]=useState(false),[error,setError]=useState(''),[result,setResult]=useState(null);
  const requestId=useMemo(()=>crypto.randomUUID(),[]);
  useEffect(()=>{if(evidence.location||!navigator.geolocation)return;navigator.geolocation.getCurrentPosition(({coords})=>{setLocation({latitude:coords.latitude,longitude:coords.longitude,accuracyMeters:coords.accuracy});setLocationWarning('')},positionError=>setLocationWarning(positionError.code===1?'Location permission was denied. You may still submit; the request will be flagged high-risk.':'Location could not be verified. You may still submit; the request will be flagged high-risk.'),{enableHighAccuracy:true,timeout:10000,maximumAge:0})},[evidence.location]);
  async function submit(){setBusy(true);setError('');try{const request=await attendanceApi.createManualRequest({action,attendanceMode,reasonCode,remarks,location,proofPhoto:evidence.photo||undefined,mismatchToken:evidence.mismatchToken||undefined,clientRequestId:requestId,deviceDetails:{browser:navigator.userAgent,deviceType:/Mobi/i.test(navigator.userAgent)?'mobile':'desktop'},biometricAttempt:{attempts:evidence.attempts||0,technicalErrorCode:evidence.technicalErrorCode,cameraStatus:evidence.cameraStatus||'not_attempted',livenessStatus:evidence.livenessStatus||'not_attempted',faceMatchStatus:evidence.faceMatchStatus||'not_attempted',faceMatchScore:evidence.faceMatchScore}});setResult(request);await submitted?.()}catch(requestError){setError(requestError.message)}finally{setBusy(false)}}
  const otherInvalid=reasonCode==='OTHER'&&remarks.trim().length<5;
  return <div className="drawer-layer"><button className="drawer-backdrop" onClick={close}/><aside className="attendance-drawer manual-attendance-drawer"><div className="drawer-heading"><div><p className="eyebrow">Controlled fallback</p><h2>Manual {action==='check_out'?'Check-Out':'Check-In'}</h2><p>Use this only when biometric attendance cannot be completed.</p></div><button onClick={close}><X size={20}/></button></div>{result?<section className="manual-success"><CheckCircle2 size={42}/><h3>Request submitted for approval</h3><p>Your official request time is <strong>{new Date(result.requestedAt).toLocaleTimeString('en-IN',{hour:'2-digit',minute:'2-digit',second:'2-digit'})}</strong>. Attendance will use this server timestamp if approved.</p><button className="primary-button" onClick={close}>Done</button></section>:<><div className="manual-policy-note"><ShieldCheck size={20}/><p><strong>Biometric attendance remains the primary method.</strong><span>HR, your manager, or an administrator will review this exception. Submission does not mark you present automatically.</span></p></div><label className="manual-field">Why can’t you use biometric attendance?<select value={reasonCode} onChange={event=>setReasonCode(event.target.value)}>{reasons.map(([value,label])=><option value={value} key={value}>{label}</option>)}</select></label><label className="manual-field">Remarks {reasonCode==='OTHER'?'(required)':'(optional)'}<textarea rows="4" maxLength="1000" value={remarks} onChange={event=>setRemarks(event.target.value)} placeholder="Add information that will help the reviewer"/></label><div className={`manual-location ${location?'verified':'warning'}`}>{location?<MapPin size={18}/>:<AlertTriangle size={18}/>}<div><strong>{location?'Location captured':'Location exception'}</strong><span>{location?`Accuracy ${Math.round(location.accuracyMeters)} metres. The server will verify the geofence.`:locationWarning}</span></div></div>{error&&<p className="attendance-error" role="alert">{error}</p>}<div className="attendance-drawer-footer"><div><Clock3 size={16}/><span>The server records the request time; your device clock is not used.</span></div><button className="primary-button" disabled={busy||otherInvalid} onClick={submit}>{busy?'Submitting…':'Submit for approval'} <ChevronRight size={15}/></button></div></>}</aside></div>
}
